mv bnsflu_3D_mpt1.las  bnsflu_3D_mpt1.ini
mv bnsflu_3D_mpt2.las  bnsflu_3D_mpt2.ini
mv bnsgra_3D_mpt1.las  bnsgra_3D_mpt1.ini
mv bnsgra_3D_mpt2.las  bnsgra_3D_mpt2.ini
mv bnsgra_3D_mpt3.las  bnsgra_3D_mpt3.ini
mv bnsgrids_3D_mpt1.las  bnsgrids_3D_mpt1.ini
mv bnsgrids_3D_mpt2.las  bnsgrids_3D_mpt2.ini
mv bnsgrids_3D_mpt3.las  bnsgrids_3D_mpt3.ini
mv bnssur_3D_mpt1.las  bnssur_3D_mpt1.ini
mv bnssur_3D_mpt2.las  bnssur_3D_mpt2.ini
