mv bnsflu_3D_mpt1.mid  bnsflu_3D_mpt1.las
mv bnsflu_3D_mpt2.mid  bnsflu_3D_mpt2.las
mv bnsgra_3D_mpt1.mid  bnsgra_3D_mpt1.las
mv bnsgra_3D_mpt2.mid  bnsgra_3D_mpt2.las
mv bnsgra_3D_mpt3.mid  bnsgra_3D_mpt3.las
mv bnsgrids_3D_mpt1.mid  bnsgrids_3D_mpt1.las
mv bnsgrids_3D_mpt2.mid  bnsgrids_3D_mpt2.las
mv bnsgrids_3D_mpt3.mid  bnsgrids_3D_mpt3.las
mv bnssur_3D_mpt1.mid  bnssur_3D_mpt1.las
mv bnssur_3D_mpt2.mid  bnssur_3D_mpt2.las
