mv bnsflu_3D_mpt1.mid  bnsflu_3D_mpt1.ini
mv bnsflu_3D_mpt2.mid  bnsflu_3D_mpt2.ini
mv bnsgra_3D_mpt1.mid  bnsgra_3D_mpt1.ini
mv bnsgra_3D_mpt2.mid  bnsgra_3D_mpt2.ini
mv bnsgra_3D_mpt3.mid  bnsgra_3D_mpt3.ini
mv bnsgrids_3D_mpt1.mid  bnsgrids_3D_mpt1.ini
mv bnsgrids_3D_mpt2.mid  bnsgrids_3D_mpt2.ini
mv bnsgrids_3D_mpt3.mid  bnsgrids_3D_mpt3.ini
mv bnssur_3D_mpt1.mid  bnssur_3D_mpt1.ini
mv bnssur_3D_mpt2.mid  bnssur_3D_mpt2.ini
