sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine_mpatch/iter_spin_BNS_CF_mpt.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine_mpatch/iter_irrot_BNS_CF_mpt.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine_mpatch/iter_corot_BNS_CF_mpt.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine_mpatch/copy_grid_parameter_from_mpt.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine_mpatch/copy_grid_parameter_to_mpt.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine_mpatch/error_metric_type2_mpt.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine_mpatch/error_metric_type3_mpt.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine_mpatch/read_parameter_mpt.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Module/grid_parameter.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine/error_surface.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine/error_metric.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine/error_matter.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine/error_matter_type2.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine/error_metric_type0.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine/error_metric_type1.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine/error_metric_type2.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine/error_velocity_potential.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine/error_metric_type2_axisym.f90
sed -i "s/\<eps\>/eps_coc/g"  ../code/Subroutine/error_adjust_parameter.f90

