cp interface.f90 interface_poisson_solver.f90
cp interface.f90 interface_poisson_solver_no_dipole.f90
cp interface.f90 interface_poisson_solver_no_lm1.f90
cp interface.f90 interface_grgrad_midpoint.f90
cp interface.f90 interface_grgrad_4th.f90
cp interface.f90 interface_interpo_linear_type0.f90
cp interface.f90 interface_interpo_linear_type0_2Dsurf.f90
cp interface.f90 interface_interpo_lag4th_2Dsurf.f90
cp interface.f90 interface_interpo_gr2fl.f90
cp interface.f90 interface_interpo_fl2gr.f90
cp interface.f90 interface_interpo_radial1p_grav.f90
cp interface.f90 interface_sourceterm_HaC.f90
cp interface.f90 interface_sourceterm_trG.f90
cp interface.f90 interface_sourceterm_MoC.f90
cp interface.f90 interface_compute_shift.f90
cp interface.f90 interface_compute_alps2alph.f90
cp interface.f90 interface_hydrostatic_eq.f90
cp interface.f90 interface_calc_surface.f90
cp interface.f90 interface_error_matter.f90
cp interface.f90 interface_update_grfield.f90
cp interface.f90 interface_update_matter.f90
cp interface.f90 interface_update_surface.f90
cp interface.f90 interface_update_parameter.f90
cp interface.f90 interface_update_parameter_axisym.f90
cp interface.f90 interface_update_parameter_triaxial.f90
cp interface.f90 interface_source_rest_mass.f90
cp interface.f90 interface_source_adm_mass.f90
cp interface.f90 interface_source_komar_mass.f90
cp interface.f90 interface_source_komar_mass_compact.f90
cp interface.f90 interface_source_proper_mass.f90
cp interface.f90 interface_source_ang_mom.f90
cp interface.f90 interface_source_ang_mom_asymp.f90
cp interface.f90 interface_source_mp_minus_madm.f90
cp interface.f90 interface_vol_int_fluid.f90
cp interface.f90 interface_vol_int_grav.f90
cp interface.f90 interface_surf_int_grav.f90
cp interface.f90 interface_radial_int_fluid.f90
cp interface.f90 interface_minv.f90
