#! /bin/sh -f
rm -i *~
rm -i */*~
rm -i */*/*~
rm -i */*/*/*~
rm -i */*/*/*/*~
rm -i *.mod
rm -i */*.mod
rm -i */*/*.mod
rm -i */*/*/*.mod
rm -i */*/*/*/*.mod
rm -i */exe_*
rm -i */*/exe_*
rm -i */*/*/exe_*
rm -i */*/*/*/exe_*
